application: tms
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: tms/public/stylesheets

- url: /js
  static_dir: tms/public/js

- url: /payload.html
  static_files: payload.html
  upload: payload.html

- url: .*
  script: main.py
