application: owneroperatortms
version: 1
runtime: python27
api_version: 1
threadsafe: True

handlers:
- url: /stylesheets
  static_dir: tms/public/stylesheets

- url: /resources
  static_dir: tms/public/resources

- url: /js
  static_dir: tms/public/js

- url: /extjs
  static_dir: tms/public/js/extjs

- url: .*
  script: tentwenty.app 


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/extjs
- ^(.*/)?.*/tests
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.jsb3
