application: owneroperatortms
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: tms/public/stylesheets

- url: /js
  static_dir: tms/public/js

- url: /extjs
  static_dir: tms/public/js/ext-4.0.2a

- url: /payload.*
  static_files: payload.html
  upload: payload.html

- url: /sencha
  static_files: sencha.html
  upload: sencha.html

- url: /streaming
  script: main_streaming.py

- url: .*
  script: main.py


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/ext-4.0.2a/examples
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*/ext-4.0.2a/examples
- ^(.*/)?.*/ext-4.0.2a/welcome
- ^(.*/)?.*/ext-4.0.2a/build[s]
- ^(.*/)?.*/ext-4.0.2a/jsbuilder
