application: owneroperatortms
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: tms/public/stylesheets

- url: /js
  static_dir: tms/public/js

- url: /extjs
  static_dir: tms/public/js/ext-4.0.2a

- url: /payload.*
  static_files: payload.html
  upload: payload.html

- url: /sencha
  static_files: sencha.html
  upload: sencha.html

- url: .*
  script: main.py
