application: tentwenty
version: 1
runtime: python27
api_version: 1
threadsafe: True

handlers:
- url: /stylesheets
  static_dir: tms/public/stylesheets

- url: /js
  static_dir: tms/public/js

- url: /extjs
  static_dir: tms/public/js/ext-4.0.2a

- url: .*
  script: tentwenty.app 


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/ext-4.0.2a/examples
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*/ext-4.0.2a/examples
- ^(.*/)?.*/ext-4.0.2a/welcome
- ^(.*/)?.*/ext-4.0.2a/build[s]
- ^(.*/)?.*/ext-4.0.2a/jsbuilder
